//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class BecasFedisalEntities : DbContext
{
    public BecasFedisalEntities()
        : base("name=BecasFedisalEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Becarios> Becarios { get; set; }
    public virtual DbSet<Carreras> Carreras { get; set; }
    public virtual DbSet<Ciclos> Ciclos { get; set; }
    public virtual DbSet<Datos_Beca> Datos_Beca { get; set; }
    public virtual DbSet<DatosAcademicos> DatosAcademicos { get; set; }
    public virtual DbSet<Desembolsos> Desembolsos { get; set; }
    public virtual DbSet<Empleados> Empleados { get; set; }
    public virtual DbSet<Estados> Estados { get; set; }
    public virtual DbSet<Incidentes> Incidentes { get; set; }
    public virtual DbSet<Niveles> Niveles { get; set; }
    public virtual DbSet<Notas> Notas { get; set; }
    public virtual DbSet<Presupuestos> Presupuestos { get; set; }
    public virtual DbSet<Programas> Programas { get; set; }
    public virtual DbSet<TipoIncidente> TipoIncidente { get; set; }
    public virtual DbSet<TipoUsuarios> TipoUsuarios { get; set; }
    public virtual DbSet<Universidades> Universidades { get; set; }
    public virtual DbSet<Usuarios> Usuarios { get; set; }
}
