//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Becarios
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Becarios()
    {
        this.Notas = new HashSet<Notas>();
        this.Presupuestos = new HashSet<Presupuestos>();
    }

    public string ID { get; set; }
    public string codigo_programa { get; set; }
    public string codigo_becario { get; set; }
    public int DatosAcademico { get; set; }
    public int Usuario { get; set; }

    public virtual Programas Programas { get; set; }
    public virtual DatosAcademicos DatosAcademicos { get; set; }
    public virtual Usuarios Usuarios { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Notas> Notas { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Presupuestos> Presupuestos { get; set; }
}

public partial class Carreras
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Carreras()
    {
        this.DatosAcademicos = new HashSet<DatosAcademicos>();
    }

    public int ID { get; set; }
    public string carrera { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DatosAcademicos> DatosAcademicos { get; set; }
}

public partial class Datos_Beca
{
    public int ID { get; set; }
    public decimal total_inicial { get; set; }
    public Nullable<decimal> ejecutado { get; set; }
    public Nullable<decimal> sin_ejecutar { get; set; }
}

public partial class DatosAcademicos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DatosAcademicos()
    {
        this.Becarios = new HashSet<Becarios>();
    }

    public int ID { get; set; }
    public int Nivel { get; set; }
    public int Universidad { get; set; }
    public int Carrera { get; set; }
    public System.DateTime fecha_inicio { get; set; }
    public System.DateTime fecha_finalizacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Becarios> Becarios { get; set; }
    public virtual Carreras Carreras { get; set; }
    public virtual Niveles Niveles { get; set; }
    public virtual Universidades Universidades { get; set; }
}

public partial class Desembolsos
{
    public int ID { get; set; }
    public int TipoDesembolso { get; set; }
    public decimal monto_desembolso { get; set; }
    public System.DateTime fecha_desembolso { get; set; }
    public int Presupuesto { get; set; }

    public virtual Presupuestos Presupuestos { get; set; }
    public virtual TipoDesembolso TipoDesembolso1 { get; set; }
}

public partial class Empleados
{
    public int ID { get; set; }
    public string correo { get; set; }
    public int Usuario { get; set; }

    public virtual Usuarios Usuarios { get; set; }
}

public partial class Estados
{
    public int ID { get; set; }
    public string nombre_estado { get; set; }
    public string descripcion { get; set; }
}

public partial class Incidentes
{
    public int ID { get; set; }
    public int TipoIncidente { get; set; }
    public string detalle { get; set; }

    public virtual TipoIncidente TipoIncidente1 { get; set; }
}

public partial class Materias
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Materias()
    {
        this.Notas = new HashSet<Notas>();
    }

    public int ID { get; set; }
    public string nombre_materia { get; set; }
    public int uv_materia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Notas> Notas { get; set; }
}

public partial class Niveles
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Niveles()
    {
        this.DatosAcademicos = new HashSet<DatosAcademicos>();
    }

    public int ID { get; set; }
    public string nivel_educativo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DatosAcademicos> DatosAcademicos { get; set; }
}

public partial class Notas
{
    public int ID { get; set; }
    public int Materia { get; set; }
    public decimal nota { get; set; }
    public int Ciclo { get; set; }
    public string tercio_superior { get; set; }
    public string Becario { get; set; }

    public virtual Becarios Becarios { get; set; }
    public virtual Materias Materias { get; set; }
}

public partial class Presupuestos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Presupuestos()
    {
        this.Desembolsos = new HashSet<Desembolsos>();
    }

    public int ID { get; set; }
    public decimal libros { get; set; }
    public decimal colegiatura { get; set; }
    public decimal manutencion { get; set; }
    public decimal matricula { get; set; }
    public decimal aranceles { get; set; }
    public decimal seguro { get; set; }
    public decimal trabajo_graduacion { get; set; }
    public string Becario { get; set; }

    public virtual Becarios Becarios { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Desembolsos> Desembolsos { get; set; }
}

public partial class Programas
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Programas()
    {
        this.Becarios = new HashSet<Becarios>();
    }

    public string nombre { get; set; }
    public string codigo { get; set; }
    public string descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Becarios> Becarios { get; set; }
}

public partial class TipoDesembolso
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoDesembolso()
    {
        this.Desembolsos = new HashSet<Desembolsos>();
    }

    public int ID { get; set; }
    public string tipo_desembolso { get; set; }
    public string descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Desembolsos> Desembolsos { get; set; }
}

public partial class TipoIncidente
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoIncidente()
    {
        this.Incidentes = new HashSet<Incidentes>();
    }

    public int ID { get; set; }
    public string tipo_incidente { get; set; }
    public string descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Incidentes> Incidentes { get; set; }
}

public partial class TipoUsuarios
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoUsuarios()
    {
        this.Usuarios = new HashSet<Usuarios>();
    }

    public int ID { get; set; }
    public string tipo_usuario { get; set; }
    public string descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuarios> Usuarios { get; set; }
}

public partial class Universidades
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Universidades()
    {
        this.DatosAcademicos = new HashSet<DatosAcademicos>();
    }

    public int ID { get; set; }
    public string universidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DatosAcademicos> DatosAcademicos { get; set; }
}

public partial class Usuarios
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuarios()
    {
        this.Becarios = new HashSet<Becarios>();
        this.Empleados = new HashSet<Empleados>();
    }

    public int ID { get; set; }
    public string Nombres { get; set; }
    public string Apellidos { get; set; }
    public string dui { get; set; }
    public string telefono { get; set; }
    public string direccion_be { get; set; }
    public string correo { get; set; }
    public System.DateTime fecha_nacimiento { get; set; }
    public int TipoUsuarios { get; set; }
    public int Estado { get; set; }
    public string contraseña { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Becarios> Becarios { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Empleados> Empleados { get; set; }
    public virtual TipoUsuarios TipoUsuarios1 { get; set; }
}
